################################################################################
# WeBWorK Online Homework Delivery System
# Copyright &copy; 2000-2018 The WeBWorK Project, http://openwebwork.sf.net/
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of either: (a) the GNU General Public License as published by the
# Free Software Foundation; either version 2, or (at your option) any later
# version, or (b) the "Artistic License" which comes with this package.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See either the GNU General Public License or the
# Artistic License for more details.
################################################################################

=head1 NAME

PGtikzjax.pl - Insert images into problems that are generated using LaTeX and
TikZ.  These images are generated in the browser using WebAssembly.  The
javascript library is based on the work of Jim Fowler.  See
https://github.com/kisonecat/tikzjax.

Note that this macro will only work for modern browsers, and will not work for
any version of Microsoft Internet Explorer.

=head1 DESCRIPTION

This is a macro for inserting svg images generated by TikZJax into problems.
Create a TikZJax image as follows:

    $image = createTikZJaxImage(<<END_TIKZ,
    \tikzset{>={Stealth}}
    \draw[<->] (-2,0) -- (2,0);
    \draw[<->] (0,-2) -- (0,2);
    \draw (0,0) circle[radius=1.5];
    END_TIKZ
        tikzLibraries => "arrows.meta"
    );

Then insert the image into the problem with

    TEXT($image);

If you are using PGML, you may also insert the image inside a
BEGIN_PGML/END_PGML block with

    [@ $image @]*

Note that when a hardcopy is generated, this macro falls back to using the
PGtikz.pl macro.

=head1 DETAILED USAGE

The first argument to createTikZJaxImage is a string that consists of the TikZ
commands that define the image.  It is generally best to use single quotes
around the string.  Escaping of special characters may be needed in some cases.

The options described below can be passed to createTikZJaxImage.

=over

=item tikzLibraries

Additional TikZ libraries to load.

=item tikzOptions

Options that will be passed to \begin{tikzpicture}.

=item texPackages

This option is used to ask TikZJax to load additional TeX packages.  The value
of this option should be a hash whose keys are the package names, and whose
value is a string consisting of options for the package.  The option string may
be the empty string C<"">.  At this time the only provided TeX packages are:
    pgfplots, tikz-3dplot, and array

=item addToPreamble

This is a string that will be added to the TeX preamble.  Do not use this to add
TeX packages or TikZ libraries.

=item loaderWidth

=item loaderHeight

A loading image will be displayed while the svg image is being generated by
TikZJax.  These settings will be used to set the width and height of the loading
image.  The units that will be used are points.  If these are not set, a width
and height of 75 points will be used.

It is recommended that these be set, as the width and height of the generated
svg image will not be known by TikZJax until after it is generated.  If these
are not set, the loading image will be displayed with height and width of 75
points, and once the image is generated image will be displayed with its natural
dimensions.  This will cause the contents of the page to move around.

To set these properly use the element inspector in the developer tools for your
browser.  Find the svg image in the element inspector after the image is
generated the first time, and obtain the width and height settings from there.
Use those (without the pt unit) for these settings.

=item scaled

Set this to 1 add the css class tikzjax-scaled-content that is provided by the
TikZJax JavaScript library to the containing div element.  The css style for
this class is defined as

    .tikzjax-scaled-content {
        width: 100%; height: 100%; overflow: visible;
    }

This means that the image will grow or shrink to the size of its container.

This option is implied if the width or height options below are set.

If this option is not set, then the containing div will have the css class
tikzjax-content.  The css style for this class is defined as

    .tikzjx-content { overflow: visible; }

=item width

=item height

Set this to the desired css width and height including css units of the
displayed image.  Note that the image will be displayed at its natural aspect
ratio.

If either of these options are set, the css class tikjax-scaled-content will be
added to the containing div element.

=item texOptions

Options used when a hardcopy is generated.  This should be a hash, and this hash
is simply passed to the C<image> method of PGbasicmacros.pl if set.

=item showConsole

Set this to 1 to show the TeX output in the browser JavaScript console.  This
should only be set when testing image generation, but should be disabled in the
finished result.  To disable, omit this option or set to 0.

=back

=cut

sub _PGtikzjax_init {
	return if $main::TikZJaxInitialized;
	if ($main::displayMode ne 'TeX') {
		# Dynamically load the tikzjax script to ensure it is executed in the library browser and set editor.
		main::TEXT(
			qq?
			<link rel="stylesheet" type="text/css" href="/webwork2_files/js/apps/TikZJax/fonts.css">
			<script>
			if (!window.TikzJax) {
				(function() {
					var script = document.createElement("script");
					script.type = "text/javascript";
					script.src = "/webwork2_files/js/apps/TikZJax/tikzjax.js";
					document.getElementsByTagName("head")[0].appendChild(script);
				})();
			}
			</script>?
		);
	}
	$main::TikZJaxInitialized = 1;
}

sub createTikZJaxImage {
	my ($tex, %options) = @_;
	my $output = "";

	if ($main::displayMode ne 'TeX') {
		if ($options{scaled} || $options{width} // "" ne "" || $options{height} // "" ne "") {
			my $cssWidth = $options{width} // "" ne "" ? "width:$options{width};" : "";
			my $cssHeight = $options{height} // "" ne "" ? "height:$options{height};" : "";
			$output .= "<div class='tikzjax-scaled-content' style='$cssWidth$cssHeight'>";
		} else {
			$output .= "<div class='tikzjax-content'>";
		}
		$output .= '<script type="text/tikz" ';
		$output .= "data-width='$options{loaderWidth}' " if $options{loaderWidth};
		$output .= "data-height='$options{loaderHeight}' " if $options{loaderHeight};
		$output .= "data-tikz-libraries='$options{tikzLibraries}' " if $options{tikzLibraries};
		$output .= "data-tikz-options='$options{tikzOptions}' " if $options{tikzOptions};
		if (ref($options{texPackages}) eq "HASH") {
			$output .= "data-tex-packages='{" .  join(",", map {
					"\"$_\":\"$options{texPackages}{$_}\""
				} keys %{$options{texPackages}}) . "}' ";
		}
		$output .= "data-add-to-preamble='$options{addToPreamble}' " if $options{addToPreamble};
		$output .= "data-show-console='true' " if $options{showConsole};

		$output .= '>' . $tex . '</script></div>';
	} else {
		my $image = new TikZImage;
		$image->ext('pdf');
		$image->imageName($main::PG->getUniqueName($image->ext));
		$image->texPackages($options{texPackages}) if $options{texPackages};
		$image->tikzLibraries($options{tikzLibraries}) if $options{tikzLibraries};
		$image->tikzOptions($options{tikzOptions}) if $options{tikzOptions};
		$image->addToPreamble($options{addToPreamble}) if $options{addToPreamble};
		$image->tex($tex);
		$output = image(insertGraph($image), %{$options{texOptions}});
	}

	return $output;
}

1;
