name: Generate and Publish PG POD and Sample Problem Documentation

on:
  # Execute the workflow anytime something is merged into or pushed to main.
  push:
    branches:
      - main

  # This allows this workflow to be triggered manually from the actions tab.
  workflow_dispatch:

jobs:
  generate-documentation:
    runs-on: ubuntu-24.04

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends --no-install-suggests \
            pandoc \
            libmojolicious-perl \
            libpandoc-wrapper-perl \
            libpod-parser-perl

      - name: Checkout pg code
        uses: actions/checkout@v4
        with:
          path: pg

      - name: Checkout webwork2 code
        uses: actions/checkout@v4
        with:
          repository: openwebwork/webwork2
          ref: main
          path: webwork2

      - name: Create output directory
        run: mkdir /home/runner/work/pg/pg/documentation

      - name: Generate sample problem documentation
        run: |
          perl pg/bin/parse-problem-doc.pl \
            --problem_dir=/home/runner/work/pg/pg/pg/tutorial/sample-problems \
            --out_dir=/home/runner/work/pg/pg/documentation/sample-problems \
            --pod_root=/pg/pod \
            --pg_doc_home=/pg/sample-problems

      - name: Generate POD
        run: |
          perl webwork2/bin/dev_scripts/generate-ww-pg-pod.pl \
          --pg-root=/home/runner/work/pg-docs/pg/pg \
          --output-dir=documentation/pod \
          --base-url=/pg/pod/

      - name: Copy index
        run: cp /home/runner/work/pg/pg/pg/tutorial/templates/index.html /home/runner/work/pg/pg/documentation/

      - name: Upload documentation html
        uses: actions/upload-pages-artifact@v3
        with:
          path: documentation

  publish-documentation:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Set the permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages.
    permissions:
      pages: write
      id-token: write

    runs-on: ubuntu-24.04
    needs: generate-documentation

    steps:
      - name: Publish to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
